DPC/Models/Entities/Trainee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DPC.Models.Entities
{
    public class Trainee
    {
        [Key]
        public int TraineeId { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        public Deanery Deanery { get; set; }
        [Required]
        public string Parish { get; set; }
        public Pathway Pathway { get; set; }
        public DateTime DateAdded { get; set; }
    }


    public enum Deanery
    {
        Kabba,
        Lokoja,
        Okene
    }

    public enum Pathway
    {
        [Display(Name = "Evangelization")]
        Evangelization = 0,
        [Display(Name ="Spirituality")]
        Spirituality = 1,
        [Display(Name = "Catechesis")]
        Catechesis =2,
        [Display(Name ="Lay Apostolate and Leadership")]
        Lay_Apostolate_and_Leadership = 3,
        [Display(Name = "Marriage and Family Life")]
        Marriage_and_Family_Life = 4,
        [Display(Name = "Liturgy and Divine Worship")]
        Liturgy_and_Divine_Worship = 5
    }
}

DPC/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DPC.Data;
using DPC.Models.Entities;

namespace DPC.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PaymentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Payments.Include(p => p.Trainee);
            return View(await applicationDbContext.ToListAsync());
        }
        public ActionResult PaymentListing(int id)
        {
            var payments = _context.Payments.Where(m => m.TraineeId == id).Include(p => p.Trainee).ToList();
            
            return View(payments);
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.Trainee)
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create(int id)
        {
            var trainee = _context.Trainees.FirstOrDefault(t => t.TraineeId == id);
            if (trainee != null)
            {
                ViewData["TraineeId"] =trainee.TraineeId;
                ViewData["TraineeName"] = $"{trainee.FirstName} {trainee.LastName}";
            }
            
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentId,TraineeId,PaymentDate,PaidTo,AmountPaid,PaymentDescription")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payment);
                payment.PaymentDate = DateTime.Now;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "TraineeId", "FirstName", payment.TraineeId);
            return View(payment);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "TraineeId", "FirstName", payment.TraineeId);
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentId,TraineeId,PaymentDate,PaidTo,AmountPaid,PaymentDescription")] Payment payment)
        {
            if (id != payment.PaymentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "TraineeId", "FirstName", payment.TraineeId);
            return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.Trainee)
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.Payments.FindAsync(id);
            _context.Payments.Remove(payment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(int id)
        {
            return _context.Payments.Any(e => e.PaymentId == id);
        }
    }
}

DPC/Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DPC.Data;
using DPC.Models.Entities;

namespace DPC.Controllers
{
    public class TraineesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TraineesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Trainees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Trainees.ToListAsync());
        }

        // GET: Trainees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .FirstOrDefaultAsync(m => m.TraineeId == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // GET: Trainees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trainees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TraineeId,FirstName,LastName,MiddleName,PhoneNumber,Deanery,Parish,Pathway,DateAdded")] Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainee);
                trainee.DateAdded = DateTime.Now;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trainee);
        }

        // GET: Trainees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) 
            {
                return NotFound();
            }

            var trainee = await _context.Trainees.FindAsync(id);
            if (trainee == null)
            {
                return NotFound();
            }
            return View(trainee);
        }

        // POST: Trainees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TraineeId,FirstName,LastName,MiddleName,PhoneNumber,Deanery,Parish,Pathway,DateAdded")] Trainee trainee)
        {
            if (id != trainee.TraineeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trainee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TraineeExists(trainee.TraineeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trainee);
        }

        // GET: Trainees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .FirstOrDefaultAsync(m => m.TraineeId == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // POST: Trainees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trainee = await _context.Trainees.FindAsync(id);
            _context.Trainees.Remove(trainee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TraineeExists(int id)
        {
            return _context.Trainees.Any(e => e.TraineeId == id);
        }

      
    }
}

DPC/Views/Trainees/Create.cshtml
@model DPC.Models.Entities.Trainee
@using DPC.Models.Entities

@{
    ViewData["Title"] = "Create";
}

<h1>Add new trainee</h1>

<h4>Trainee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deanery" class="control-label"></label>
                <select asp-for="Deanery" class="form-control" asp-items="Html.GetEnumSelectList<Deanery>()"></select>
                <span asp-validation-for="Deanery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parish" class="control-label"></label>
                <input asp-for="Parish" class="form-control" />
                <span asp-validation-for="Parish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pathway" class="control-label"></label>
                <select asp-for="Pathway" class="form-control" asp-items="Html.GetEnumSelectList<Pathway>()"></select>
                <span asp-validation-for="Pathway" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DPC/Views/Trainees/Delete.cshtml
@model DPC.Models.Entities.Trainee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deanery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deanery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parish)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parish)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pathway)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pathway)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TraineeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DPC/Views/Trainees/Details.cshtml
@model DPC.Models.Entities.Trainee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Trainee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deanery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deanery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parish)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parish)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pathway)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pathway)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TraineeId">Edit</a> |
    <a asp-action="Create" asp-controller="Payments" asp-route-id="@Model.TraineeId">Add Payment</a> |
    <a asp-action="PaymentListing" asp-controller="Payments" asp-route-id="@Model.TraineeId">Payment History</a> |
    <a asp-action="Index">Back to List</a> |
</div>

DPC/Views/Trainees/Edit.cshtml
@model DPC.Models.Entities.Trainee
@using DPC.Models.Entities

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Trainee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TraineeId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deanery" class="control-label"></label>
                <select asp-for="Deanery" class="form-control" asp-items="Html.GetEnumSelectList<Deanery>()"></select>
                <span asp-validation-for="Deanery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parish" class="control-label"></label>
                <input asp-for="Parish" class="form-control" />
                <span asp-validation-for="Parish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pathway" class="control-label"></label>
                <select asp-for="Pathway" class="form-control" asp-items="Html.GetEnumSelectList<Pathway>()"></select>
                <span asp-validation-for="Pathway" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DPC/Views/Trainees/Index.cshtml
@model IEnumerable<DPC.Models.Entities.Trainee>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deanery)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parish)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pathway)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deanery)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parish)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pathway)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAdded)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TraineeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TraineeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TraineeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>